---
abstract: 'build complex conditions out of other conditions'
author:
  - 'Ruslan Zakirov <Ruslan.Zakirov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Condition-Complex
no_index:
  directory:
    - etc
    - inc
    - t
requires:
  Parse::BooleanLogic: 0
  Regexp::Common: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
